### PR TITLE
Hacktoberfest Second Commit

### PR DESCRIPTION
**Pull request by kiran11621**
1.  .$db->error() corrected this on task1.php
2.  Added Heading to the task1.php with underline to heading
3.  Correct Spell of Full in form of task1.php
4.  Aligned center with underline in task3.php
5.  Correct SR.No to SR. No.

### CODE REVIEW

**Comment by kiran11621** [comment]
Please let me know if any mistake. Doing for first time.
Thank You

**Review by Ali-Murtaza143 — APPROVED** [review]
hacktoberfest-accepted

**Comment by Ali-Murtaza143** [comment]
Write hacktoberfest in commit and rest things fine

**Comment by Ali-Murtaza143** [comment]
I have accepted one request go and see in hacktoberfest website

**Comment by kiran11621** [comment]
> I have accepted one request go and see in hacktoberfest website

Thank You soo much Sir

**Pull request merged**
